# Generated by Django 5.2.1 on 2026-06-03 13:39

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_customer_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload('images', 'customer'), verbose_name='تصویر پروفایل'),
        ),
    ]
